### ISSUE TITLE
Blue-Green deployments need to allow a `git_hash` variable.

### ISSUE THREAD

**Issue by JoelRobinson-Tista** [department-of-veterans-affairs/appeals-devops-jenkins#12]
Update blueGreen.groovy to allow rollbacks to a previous AMI. 

Either we need some way to specify the git_hash variable in the Groovy script or we need a way to pass extra variables into blueGreen.groovy.

**Comment by skeenb** [comment]
Resolved by these three PRs
https://github.com/department-of-veterans-affairs/appeals-terraform/pull/367
https://github.com/department-of-veterans-affairs/appeals-deployment/pull/3317
https://github.com/department-of-veterans-affairs/appeals-devops-jenkins/pull/15
